"""
renpy_builder.py

Minimal RenPy game builder. Takes a game definition and outputs a complete,
distributable RenPy game (including a runnable executable via the RenPy SDK).

SETUP
-----
1. Install the RenPy SDK: https://www.renpy.org/latest.html
2. Set RENPY_SDK environment variable to the SDK root, OR pass --sdk on the CLI.
   e.g. export RENPY_SDK=/path/to/renpy-8.x.x-sdk
3. Place your static template files alongside this script in renpy_templates/:
     renpy_templates/screens.rpy   (copy from any SDK-generated project)
     renpy_templates/gui.rpy       (copy from any SDK-generated project)
   These are boilerplate files that never change between games.

USAGE
-----
  python renpy_builder.py                        # runs built-in example
  python renpy_builder.py game.json              # builds from JSON file
  python renpy_builder.py game.json --sdk /path  # explicit SDK path
  python renpy_builder.py game.json --no-dist    # write project only, skip distribution build

Game definition format:
{
    "title": "My Game",
    "output_dir": "my_game",
    "characters": [
        {"id": "alice", "name": "Alice", "color": "#c8ffc8"}
    ],
    "images": [
        {"id": "bg school", "file": "school.jpg"}
    ],
    "scenes": [
        {
            "background": "bg school",
            "lines": [
                {"who": "alice", "say": "Hello!"},
                {"who": null,    "say": "The narrator speaks."}
            ]
        }
    ]
}
"""

import json
import os
import platform
import re
import shutil
import subprocess
import sys
import textwrap


# Where static template files live, relative to this script
TEMPLATES_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "renpy_templates")


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def build_game(definition: dict, output_dir: str = None, sdk_path: str = None, distribute: bool = True) -> dict:
    """
    Build a RenPy game from a definition dict.

    Args:
        definition:  Game definition (see module docstring).
        output_dir:  Where to write the project folder. Overrides definition["output_dir"].
        sdk_path:    Path to the RenPy SDK root. Falls back to RENPY_SDK env var.
        distribute:  If True, call the SDK to build a distributable executable package.

    Returns:
        Dict with at least {"project_dir": str}. Includes "dist_stdout"/"dist_stderr" if distributed.
    """
    title      = definition.get("title", "Untitled Game")
    characters = definition.get("characters", [])
    images     = definition.get("images", [])
    scenes     = definition.get("scenes", [])
    out        = output_dir or definition.get("output_dir", "renpy_output")

    game_dir   = os.path.join(out, "game")
    images_dir = os.path.join(game_dir, "images")
    os.makedirs(game_dir, exist_ok=True)
    os.makedirs(images_dir, exist_ok=True)

    # --- Write generated files ---
    _write_options(game_dir, title)
    _write_script(game_dir, characters, images, scenes)

    # --- Copy static template files ---
    _copy_templates(game_dir)

    print(f"[renpy_builder] Project written to: {os.path.abspath(out)}/")

    result = {"project_dir": os.path.abspath(out)}

    # --- Optionally build distributable ---
    if distribute:
        sdk = sdk_path or os.environ.get("RENPY_SDK", "")
        if not sdk:
            print("[renpy_builder] WARNING: No SDK path provided and RENPY_SDK not set.")
            print("                Set RENPY_SDK=/path/to/sdk or use --sdk to build a distributable.")
            print("                The project files are ready — open them in the RenPy launcher to build manually.")
            return result
        dist_result = _distribute(out, sdk)
        result.update(dist_result)

    return result


# ---------------------------------------------------------------------------
# File writers
# ---------------------------------------------------------------------------

def _write_options(game_dir: str, title: str):
    """Write options.rpy — game metadata and build config."""
    safe_title = re.sub(r"[^A-Za-z0-9_]", "", title.replace(" ", "_")) or "UntitledGame"
    content = textwrap.dedent(f"""\
        ## options.rpy — generated by renpy_builder

        define config.name = "{title}"
        define config.version = "1.0"
        define config.window_icon = None
        define gui.show_name = True
        define config.save_directory = "{safe_title}"

        ## Build configuration
        init python:
            build.name = "{safe_title}"
            build.executable_name = "{safe_title}"
            build.directory_name = "{safe_title}-1.0"
    """)
    _write(os.path.join(game_dir, "options.rpy"), content)


# ---------------------------------------------------------------------------
# Template copying
# ---------------------------------------------------------------------------

def _copy_templates(game_dir: str):
    """
    Copy static boilerplate files from renpy_templates/ into the project.
    These files are standard RenPy boilerplate that never change between games.
    Copy them from any SDK-generated project (e.g. the_question).
    """
    required_files = ["screens.rpy", "gui.rpy"]
    missing = []

    for filename in required_files:
        src = os.path.join(TEMPLATES_DIR, filename)
        dst = os.path.join(game_dir, filename)
        if os.path.exists(src):
            shutil.copy2(src, dst)
            print(f"[renpy_builder]   copied {filename}")
        else:
            missing.append(src)

    # GUI assets folder (textbox, buttons, etc.)
    gui_src = os.path.join(TEMPLATES_DIR, "gui")
    gui_dst = os.path.join(game_dir, "gui")
    if os.path.isdir(gui_src):
        if os.path.exists(gui_dst):
            shutil.rmtree(gui_dst)
        shutil.copytree(gui_src, gui_dst)
        print("[renpy_builder]   copied gui/")
    else:
        missing.append(gui_src)

    if missing:
        print("[renpy_builder] WARNING: Missing template files:")
        for path in missing:
            print(f"  {path}")
        print(f"  Copy screens.rpy, gui.rpy, and gui/ from any RenPy SDK project into: {TEMPLATES_DIR}/")
        print("  Without these, the game will crash on launch.")


# ---------------------------------------------------------------------------
# Distribution build
# ---------------------------------------------------------------------------

def _distribute(project_dir: str, sdk_path: str) -> dict:
    """Call the RenPy SDK to build a distributable executable package."""
    sdk_path = os.path.abspath(sdk_path)

    if not os.path.isdir(sdk_path):
        print(f"[renpy_builder] ERROR: SDK path does not exist: {sdk_path}")
        return {"dist_error": f"SDK path does not exist: {sdk_path}"}

    # Find the right renpy executable for this platform
    # distribute is a command of the launcher project, not the game project.
    # Correct syntax: renpy.sh <sdk>/launcher distribute <project>
    launcher_dir = os.path.join(sdk_path, "launcher")
    system = platform.system()
    if system == "Windows":
        renpy_bin = os.path.join(sdk_path, "renpy.exe")
        if not os.path.exists(renpy_bin):
            py = _find_sdk_python(sdk_path)
            cmd = [py, os.path.join(sdk_path, "renpy.py"), launcher_dir, "distribute", os.path.abspath(project_dir)]
        else:
            cmd = [renpy_bin, launcher_dir, "distribute", os.path.abspath(project_dir)]
    else:
        renpy_sh = os.path.join(sdk_path, "renpy.sh")
        if not os.path.exists(renpy_sh):
            print(f"[renpy_builder] ERROR: renpy.sh not found in SDK: {sdk_path}")
            return {"dist_error": f"renpy.sh not found in SDK: {sdk_path}"}
        cmd = [renpy_sh, launcher_dir, "distribute", os.path.abspath(project_dir)]

    print("[renpy_builder] Building distribution...")
    print(f"  SDK:     {sdk_path}")
    print(f"  Project: {os.path.abspath(project_dir)}")
    print(f"  Command: {' '.join(cmd)}")

    try:
        proc = subprocess.run(
            cmd, capture_output=True, text=True,
            stdin=subprocess.DEVNULL, timeout=60,
        )
        if proc.returncode == 0:
            print("[renpy_builder] Distribution built successfully.")
        else:
            print(f"[renpy_builder] Distribution build failed (exit {proc.returncode}).")
            if proc.stdout:
                print(proc.stdout)
            if proc.stderr:
                print(proc.stderr, file=sys.stderr)
        return {
            "dist_returncode": proc.returncode,
            "dist_stdout":     proc.stdout,
            "dist_stderr":     proc.stderr,
        }
    except subprocess.TimeoutExpired as e:
        print(f"[renpy_builder] ERROR: SDK timed out after {e.timeout}s (likely waiting for input).")
        return {"dist_returncode": -1, "dist_error": f"timeout after {e.timeout}s"}
    except Exception as e:
        print(f"[renpy_builder] ERROR running SDK: {e}")
        return {"dist_error": str(e)}


def _find_sdk_python(sdk_path: str) -> str:
    """Find the bundled Python interpreter inside the SDK (Windows fallback)."""
    lib = os.path.join(sdk_path, "lib")
    if os.path.isdir(lib):
        for entry in os.listdir(lib):
            if entry.startswith("py3-windows"):
                py = os.path.join(lib, entry, "python.exe")
                if os.path.exists(py):
                    return py
    return "python"  # last resort


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _write_script(game_dir: str, characters: list, images: list, scenes: list):
    lines = []

    char_has_image = {c["id"] for c in characters if c.get("image_file")}

    # --- Character definitions ---
    lines.append("## Characters")
    for char in characters:
        cid = char["id"]
        name = char["name"]
        color = char.get("color", "#ffffff")
        lines.append(f'define {cid} = Character("{name}", color="{color}")')
    lines.append("")

    # --- Image definitions ---
    lines.append("## Images")
    for img in images:
        lines.append(f'image {img["id"]} = "images/{img["file"]}"')
    for char in characters:
        if char.get("image_file"):
            lines.append(f'image {char["id"]} = "images/{char["image_file"]}"')
    lines.append("")

    # --- Title screen label ---
    lines.append("## Title screen")
    lines.append("label splashscreen:")
    lines.append("    return")
    lines.append("")
    lines.append("label main_menu:")
    lines.append("    return")
    lines.append("")

    # --- Start label ---
    lines.append("## Game start")
    lines.append("label start:")
    lines.append("")

    # --- Scenes ---
    shown_chars: set = set()
    for i, scene in enumerate(scenes):
        bg = scene.get("background")

        # Hide sprites before scene transition
        for cid in shown_chars:
            lines.append(f"    hide {cid}")
        shown_chars = set()

        if bg:
            if i == 0:
                lines.append(f"    scene {bg}")
            else:
                lines.append(f"    scene {bg} with dissolve")
        else:
            if i == 0:
                lines.append("    scene black")

        for line in scene.get("lines", []):
            who = line.get("who")
            say = (line.get("say", "")
                   .replace("\\", "\\\\")
                   .replace('"', '\\"')
                   .replace("[", "[[")
                   .replace("]", "]]")
                   .replace("{", "{{")
                   .replace("}", "}}")
                   .replace("\r", "")
                   .replace("\n", " "))
            if who and who in char_has_image and who not in shown_chars:
                lines.append(f"    show {who}")
                shown_chars.add(who)
            if who:
                lines.append(f'    {who} "{say}"')
            else:
                lines.append(f'    "{say}"')

        lines.append("")

    # Hide any remaining sprites before end
    for cid in shown_chars:
        lines.append(f"    hide {cid}")

    # --- End ---
    lines.append('    "The End."')
    lines.append("")
    lines.append("    return")
    lines.append("")

    _write(os.path.join(game_dir, "script.rpy"), "\n".join(lines))


def _write(path: str, content: str):
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

EXAMPLE_DEFINITION = {
    "title": "A Short Story",
    "output_dir": "example_game",
    "characters": [
        {"id": "alice", "name": "Alice", "color": "#c8ffc8"},
        {"id": "bob",   "name": "Bob",   "color": "#c8c8ff"},
    ],
    "images": [
        {"id": "bg forest", "file": "forest.jpg"},
        {"id": "bg town",   "file": "town.jpg"},
    ],
    "scenes": [
        {
            "background": "bg forest",
            "lines": [
                {"who": None,    "say": "Deep in the forest, two friends met."},
                {"who": "alice", "say": "Bob! I've been looking for you."},
                {"who": "bob",   "say": "Alice... we need to talk."},
            ]
        },
        {
            "background": "bg town",
            "lines": [
                {"who": None,    "say": "They walked back to town together."},
                {"who": "alice", "say": "Whatever happens, we face it together."},
                {"who": "bob",   "say": "Together, then."},
            ]
        }
    ]
}


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Build a RenPy game from a JSON definition.")
    parser.add_argument("definition", nargs="?", help="Path to game definition JSON file. Omit to run built-in example.")
    parser.add_argument("--sdk",      help="Path to RenPy SDK root (overrides RENPY_SDK env var)")
    parser.add_argument("--out",      help="Output directory (overrides output_dir in definition)")
    parser.add_argument("--no-dist",  action="store_true", help="Write project files only; skip distribution build")
    args = parser.parse_args()

    if args.definition:
        with open(args.definition) as f:
            definition = json.load(f)
    else:
        print("[renpy_builder] No definition file provided — running built-in example.")
        definition = EXAMPLE_DEFINITION

    build_game(
        definition,
        output_dir=args.out,
        sdk_path=args.sdk,
        distribute=not args.no_dist,
    )