"""Worldgen seeding folded into run_build: a world-flagged spec pre-seeds world.ts via the bridge
and forces a single-file (main.ts) manifest, so the planner is bypassed and the model authors gameplay
on top. worldgen_bridge.build and the AgentLoop are stubbed — no worldgen run, no live model.
"""

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from tools.execution_context import execution_context
from maestro.state import RunState
from maestro.codegen.gates import game_dir, read_manifest
import maestro.codegen.run as run_mod


def _world_spec():
    return {"request": "a cozy village RPG", "title": "Willowmere", "mode": "3d",
            "world": {"settlement": "Willowmere", "size": "medium",
                      "biomes": ["grassland", "forest", "hill"]},
            "design": {"title": "Willowmere", "mode": "3d",
                       "entities": [{"id": "baker", "desc": "a friendly baker in an apron"},
                                    {"id": "coin", "desc": "a small gold coin"}],
                       "win": "deliver bread to every villager", "lose": "none"},
            "frozen": True}


@pytest.fixture
def stub_bridge(monkeypatch):
    """Fake worldgen_bridge.build: record the recipe, write a minimal generated world.ts."""
    calls = {}

    def fake_build(recipe, out_dir: Path):
        calls["recipe"] = recipe
        calls["out_dir"] = Path(out_dir)
        (Path(out_dir)).mkdir(parents=True, exist_ok=True)
        (Path(out_dir) / "world.ts").write_text(
            "// GENERATED by worldgen\nexport const WORLD: any = {};\n", encoding="utf-8")
        return {"gw": 20, "gh": 18, "buildings": [{"id": "b1"}, {"id": "b2"}]}

    import maestro.codegen.worldgen_bridge as wb
    monkeypatch.setattr(wb, "build", fake_build)
    return calls


def test_recipe_from_spec_reflects_requested_setting():
    recipe = run_mod._recipe_from_spec(_world_spec())
    assert recipe["size"] == "medium"
    assert recipe["palette"]["biomes"] == ["grassland", "forest", "hill"]
    loc = recipe["locations"][0]
    assert loc["type"] == "settlement" and loc["name"] == "Willowmere" and loc["id"] == "willowmere"


def test_main_purpose_is_spec_driven_not_hardcoded_village():
    purpose = run_mod._world_main_purpose(_world_spec())
    assert "baker" in purpose and "deliver bread to every villager" in purpose
    assert "Rivervale" not in purpose               # the old hardcoded village is gone
    assert 'spawnWorld' in purpose and 'heightAt' in purpose


def test_maybe_seed_writes_world_and_forces_single_file_manifest(tmp_path, stub_bridge):
    with execution_context(working_directory=str(tmp_path)):
        rid = run_mod.create_run("u1")
        st = RunState.for_run(rid)
        run_mod._maybe_seed_worldgen(rid, st, _world_spec())

        gd = game_dir(st.run_dir)
        assert (gd / "world.ts").exists()                       # bridge wrote world.ts
        assert stub_bridge["recipe"]["locations"][0]["name"] == "Willowmere"

        files = read_manifest(st.run_dir)["files"]
        assert [f["name"] for f in files] == ["main.ts"]        # planner bypassed: only main.ts
        assert "deliver bread to every villager" in files[0]["purpose"]


def test_maybe_seed_is_idempotent(tmp_path, stub_bridge):
    with execution_context(working_directory=str(tmp_path)):
        rid = run_mod.create_run("u1")
        st = RunState.for_run(rid)
        run_mod._maybe_seed_worldgen(rid, st, _world_spec())
        (game_dir(st.run_dir) / "world.ts").write_text("edited", encoding="utf-8")
        stub_bridge.clear()
        run_mod._maybe_seed_worldgen(rid, st, _world_spec())    # re-entry: world.ts exists → no-op
        assert stub_bridge == {}                                # bridge NOT called again
        assert (game_dir(st.run_dir) / "world.ts").read_text() == "edited"


def test_maybe_seed_noop_when_not_world_flagged(tmp_path, stub_bridge):
    with execution_context(working_directory=str(tmp_path)):
        rid = run_mod.create_run("u1")
        st = RunState.for_run(rid)
        spec = _world_spec()
        spec["world"] = None
        run_mod._maybe_seed_worldgen(rid, st, spec)
        assert not (game_dir(st.run_dir) / "world.ts").exists()
        assert stub_bridge == {}


def test_run_build_seeds_world_before_loop(tmp_path, stub_bridge, monkeypatch):
    """run_build on a world-flagged frozen spec seeds world.ts + the single-file manifest before the
    driving loop runs. AgentLoop and the connector are stubbed so no model is called."""
    class _Result:
        ok, steps, failures, elapsed = False, 0, [], 0.0

    class _FakeLoop:
        def __init__(self, *a, **k):
            _FakeLoop.seen_world = (game_dir(RunState.for_run(rid).run_dir) / "world.ts").exists()

        def run(self):
            return _Result()

    monkeypatch.setattr("maestro.agent_loop.AgentLoop", _FakeLoop)
    monkeypatch.setattr("llm_clients.connector_selector.get_connector", lambda: object())

    with execution_context(working_directory=str(tmp_path)):
        rid = run_mod.create_run("u1")
        st = RunState.for_run(rid)
        st.write_spec(_world_spec())
        result = run_mod.run_build(rid, max_steps=1)

        assert result.ok is False
        assert _FakeLoop.seen_world is True                     # world.ts existed by the time the loop built
        files = read_manifest(st.run_dir)["files"]
        assert [f["name"] for f in files] == ["main.ts"]
