"""The two pre-seeds run_build lays down before the loop, on ORTHOGONAL axes: worldgen writes
world.ts (the PLACE) for a world-flagged spec, the scaffold writes main.ts (the CONTROLS) for every
spec. Both are seed-if-absent, so a rebuild/fix/reskin never regenerates one under a half-built
game. worldgen_bridge.build and the AgentLoop are stubbed — no worldgen run, no live model.
"""

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

import tempfile

import maestro.codegen.run as run_mod
import maestro.codegen.worldgen_bridge as wb
from maestro.codegen.gates import game_dir
from maestro.codegen.tools import _cap_chars, _elide_long_lines
from maestro.codegen.worldgen_bridge import _ts_shape, _write_world_ts
from maestro.state import RunState
from tools.execution_context import execution_context


def _world_spec():
    return {"request": "a cozy village RPG", "title": "Willowmere", "mode": "3d",
            "world": {"settlement": "Willowmere", "size": "medium",
                      "biomes": ["grassland", "forest", "hill"]},
            "design": {"title": "Willowmere", "mode": "3d",
                       "control": {"entity": "player", "scheme": "first-person-3d"},
                       "entities": [{"id": "baker", "desc": "a friendly baker in an apron"},
                                    {"id": "coin", "desc": "a small gold coin"}],
                       "win": "deliver bread to every villager", "lose": "none"},
            "frozen": True}


@pytest.fixture
def stub_bridge(monkeypatch):
    """Fake worldgen_bridge.build: record the recipe, write a minimal generated world.ts."""
    calls = {}

    def fake_build(recipe, out_dir: Path):
        calls["recipe"] = recipe
        calls["out_dir"] = Path(out_dir)
        (Path(out_dir)).mkdir(parents=True, exist_ok=True)
        (Path(out_dir) / "world.ts").write_text(
            "// GENERATED by worldgen\nexport const WORLD: any = {};\n", encoding="utf-8")
        return {"gw": 20, "gh": 18, "buildings": [{"id": "b1"}, {"id": "b2"}]}

    monkeypatch.setattr(wb, "build", fake_build)
    return calls


def test_recipe_from_spec_reflects_requested_setting():
    recipe = wb._recipe_from_spec(_world_spec())
    assert recipe["size"] == "medium"
    assert recipe["palette"]["biomes"] == ["grassland", "forest", "hill"]
    loc = recipe["locations"][0]
    assert loc["type"] == "settlement" and loc["name"] == "Willowmere" and loc["id"] == "willowmere"


def test_seed_writes_both_the_world_and_the_control_scaffold(tmp_path, stub_bridge):
    """The merge: a world spec gets BOTH seeds. worldgen owns the place, the scaffold owns the
    controls, and no manifest is forced — the planner runs and decomposes like any other game."""
    with execution_context(working_directory=str(tmp_path)):
        rid = run_mod.create_run("u1")
        st = RunState(rid)
        run_mod._seed(rid, st, _world_spec())

        gd = game_dir(st.run_dir)
        assert (gd / "world.ts").exists()                       # bridge wrote the place
        assert stub_bridge["recipe"]["locations"][0]["name"] == "Willowmere"

        main = (gd / "main.ts").read_text()
        assert main.startswith("// GENERATED control scaffold")  # scaffold wrote the controls
        assert 'controls: "fp"' in main                          # the spec's OWN scheme, not a default
        assert not (gd / "manifest.json").exists()               # planner NOT bypassed


def test_seed_is_idempotent_per_file(tmp_path, stub_bridge):
    with execution_context(working_directory=str(tmp_path)):
        rid = run_mod.create_run("u1")
        st = RunState(rid)
        run_mod._seed(rid, st, _world_spec())
        gd = game_dir(st.run_dir)
        (gd / "world.ts").write_text("edited world", encoding="utf-8")
        (gd / "main.ts").write_text("edited main", encoding="utf-8")
        stub_bridge.clear()
        run_mod._seed(rid, st, _world_spec())                   # re-entry: both exist → no-op
        assert stub_bridge == {}                                # bridge NOT called again
        assert (gd / "world.ts").read_text() == "edited world"
        assert (gd / "main.ts").read_text() == "edited main"


def test_seed_skips_worldgen_when_not_world_flagged(tmp_path, stub_bridge):
    with execution_context(working_directory=str(tmp_path)):
        rid = run_mod.create_run("u1")
        st = RunState(rid)
        spec = _world_spec()
        spec["world"] = None
        run_mod._seed(rid, st, spec)
        assert not (game_dir(st.run_dir) / "world.ts").exists()
        assert stub_bridge == {}
        assert (game_dir(st.run_dir) / "main.ts").exists()       # ...but the scaffold still lands


def test_run_build_seeds_both_before_loop(tmp_path, stub_bridge, monkeypatch):
    """run_build on a world-flagged frozen spec has world.ts AND the control scaffold on disk before
    the driving loop runs. AgentLoop and the connector are stubbed so no model is called."""
    class _Result:
        ok, steps, failures, elapsed = False, 0, [], 0.0

    class _FakeLoop:
        def __init__(self, *a, **k):
            gd = game_dir(RunState(rid).run_dir)
            _FakeLoop.seen = ((gd / "world.ts").exists(), (gd / "main.ts").exists())

        def run(self):
            return _Result()

    monkeypatch.setattr(run_mod, "AgentLoop", _FakeLoop)
    monkeypatch.setattr(run_mod, "get_connector", lambda: object())

    with execution_context(working_directory=str(tmp_path)):
        rid = run_mod.create_run("u1")
        st = RunState(rid)
        st.write_spec(_world_spec())
        result = run_mod.run_build(rid, max_steps=1)

        assert result.ok is False
        assert _FakeLoop.seen == (True, True)                   # both seeds landed before the loop built


def test_world_ts_carries_schema_header_surviving_read_elision():
    """The WORLD literal is a 100KB single line the read tool elides; the schema-bearing keys
    (buildings/grass/plaza/...) sit inside it. A generated shape comment must survive elision so the
    model spawns from real field names instead of guessing (a wrong name → undefined → y=NaN)."""

    assert _ts_shape({"x": 1.0, "z": 3.0, "h": 0.9}) == "{x, z, h}"
    assert _ts_shape([[-33.0, -23.0], [-31.0, -23.0]]) == "[number, number][]"
    assert _ts_shape([[0.6] * 34] * 24) == "number[][]"          # a heightfield grid, not a tuple
    assert _ts_shape([{"id": "well", "x": 1.0}]) == "{id, x}[]"

    data = {"cell": 2.0, "gw": 34, "gh": 24, "seed": 0,
            "height": [[0.5] * 34 for _ in range(24)],
            "color": [["#abc"] * 34 for _ in range(24)],
            "buildings": [{"id": "well", "label": "stone well", "x": 1.0, "z": 1.0}],
            "grass": [[-33.0, -23.0]], "grass_points": [[-33.0, 0.6, -22.0]],
            "props": [{"x": -7.0, "y": 0.8, "z": -23.0, "r": 0.5, "color": "#70747a"}],
            "plaza": {"x": 1.0, "z": 3.0, "h": 0.9}, "gate": {"x": -9.0, "z": 23.0}}

    with tempfile.TemporaryDirectory() as d:
        p = Path(d) / "world.ts"
        _write_world_ts(p, data)
        served, elided = _elide_long_lines(p.read_text())
        served, _ = _cap_chars(served)

    assert elided is True                                        # the giant WORLD literal was cut
    assert "WORLD shape" in served                               # ...but the schema survived
    for key in data:                                             # every field name is visible
        assert f"//   {key}:" in served
    assert "plaza: {x, z, h}" in served                          # a schema buried mid-literal
    assert "returns NaN ONLY when x or z is itself NaN/undefined" in served  # the heightAt contract
