"""Region composition — I_r^comp (§2.3.2, eq. 9).

    I_r^comp = G_image(I_r^terrain, P_r, I_concept)

The composition is generated by editing a render of the terrain that already
exists, not by drawing a region from nothing. That is the whole point: the
render carries the local topography, the material appearance, the light and the
viewing direction, so what comes back is the same ground with objects standing
on it, seen from a camera we chose and recorded.

It is a 2D layout prior and nothing more. No geometry is decided here — the
composition says what is in the region and where it sits in the frame, and the
stages after this turn that into meshes and placements.

The paper's G_image is GPT-Image-2. Here it is Qwen Image Edit, conditioned on
the terrain render first and the concept image second, which is what the edit
model's two reference slots are for.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np

from ..backends import ImageModel
from ..planning.models import ScenePlan
from ..terrain.models import TerrainPlan
from ..terrain.render import render
from .camera import Camera, frame_width_for, region_camera
from .models import RegionalSpec

# What must not appear. A composition that adds people or invents a horizon has
# stopped being an edit of our terrain, and everything downstream reads it as if
# it were still that terrain.
COMPOSITION_NEGATIVE = (
    "text, watermark, ui, map, diagram, collage, split screen, illustration, "
    "cartoon, people, faces, animals, different terrain, changed horizon, "
    "changed camera angle, blurry, low detail"
)


def describe(spec: RegionalSpec, scene: ScenePlan, camera: Camera, frame_m: float) -> str:
    """P_r as the instruction the edit model is given.

    Counts are stated literally and sizes in metres alongside the width of the
    ground in frame, because "a jeep" and "a 4 m jeep across 25 m of ground" are
    different pictures and only one of them can be placed afterwards.
    """
    lines = [
        f"Keep this terrain exactly as it is — same ground, same rock, same "
        f"horizon, same camera. Add objects standing on it.",
        f"",
        f"The view spans about {frame_m:.0f} m of ground from left to right, "
        f"looking down at about {_pitch_deg(camera):.0f} degrees.",
        f"",
        f"This is {spec.function}",
        f"",
        f"Place:",
    ]
    for obj in spec.objects:
        if obj.approx_count is not None:
            amount = f"{obj.approx_count}"
        else:
            area = frame_m * frame_m / 100.0
            amount = f"about {max(1, round(obj.density_per_100m2 * area))}"
        lines.append(
            f"- {amount} x {obj.category}, about {obj.typical_size_m:g} m across. "
            f"{obj.appearance}"
        )
    if spec.spatial:
        lines += ["", "Arranged so that:"]
        lines += [f"- {r.subject} {r.relation} {r.target}." for r in spec.spatial]
    lines += [
        "",
        f"{spec.appearance}",
        f"Overall style: {scene.globals.visual_style} "
        f"Light: {scene.globals.atmosphere}",
        "",
        "Photographic, sharp, natural light. Every object fully in frame and "
        "clearly separated from the others, resting on the ground.",
    ]
    return "\n".join(lines)


def _pitch_deg(camera: Camera) -> float:
    position = np.asarray(camera.position, dtype=float)
    target = np.asarray(camera.target, dtype=float)
    direction = target - position
    return float(np.degrees(np.arcsin(-direction[1] / np.linalg.norm(direction))))


def terrain_view(
    plan: TerrainPlan,
    spec: RegionalSpec,
    out_dir: Path | str,
    *,
    height: np.ndarray | None = None,
    width: int = 1216,
    height_px: int = 832,
) -> tuple[Path, Camera, float]:
    """Render I_r^terrain and return it with the camera that made it.

    The camera is returned rather than recomputed later. It is kappa_r, and
    every placement in this region is expressed against it.
    """
    out_dir = Path(out_dir)
    if height is None:
        height = np.load(out_dir / "heightmap.npy").astype(np.float32)
    frame_m = frame_width_for([o.typical_size_m for o in spec.objects])
    camera = region_camera(
        plan, height, spec.region_id, frame_m, width=width, height_px=height_px
    )
    name = f"region_{spec.region_id}_terrain.png"
    render(
        plan, out_dir,
        cameras=[camera.shot(name)],
        resolution=f"{camera.width}x{camera.height}",
    )
    return out_dir / name, camera, frame_m


def compose(
    spec: RegionalSpec,
    scene: ScenePlan,
    terrain_image: Path | str,
    camera: Camera,
    frame_m: float,
    out: Path | str,
    *,
    images: ImageModel | None = None,
    concept: Path | str | None = None,
    seed: int = 17,
    denoise: float = 0.86,
) -> Path:
    """Generate I_r^comp from the terrain render, P_r and the concept image.

    `denoise` is the whole tension of this stage in one number. Too low and the
    model declines to add anything; too high and it redraws the ground, which
    breaks the correspondence the placement stage depends on.
    """
    images = images or ImageModel()
    references = [Path(terrain_image)]
    if concept is not None and Path(concept).exists():
        references.append(Path(concept))
    return images.edit(
        describe(spec, scene, camera, frame_m),
        references,
        out,
        negative=COMPOSITION_NEGATIVE,
        seed=seed,
        denoise=denoise,
    )


__all__ = ["compose", "terrain_view", "describe", "COMPOSITION_NEGATIVE"]
